import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/toaster";

import "@stream-io/video-react-sdk/dist/css/styles.css";
import "react-datepicker/dist/react-datepicker.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClerkProvider

      appearance={{
      layout: {
        logoImageUrl: '/icons/logo.png',
        socialButtonsVariant: 'iconButton'
      },

        variables: {
          colorText: '#fff',
          colorPrimary: '#000000',
          colorBackground: '#444444'

        }
      }}
      >
      <body className={`${inter.className} bg-dark-2`}>{children}
      <Toaster />
      </body>
      </ClerkProvider>
    </html>
  );
}
